#ifndef LOGINWINDOW_H
#define LOGINWINDOW_H

#include <QDialog>
#include <QString> // 确保 QString 被包含

// Forward declaration for the UI class generated by Qt Designer
namespace Ui {
class LoginWindow;
}

// Forward declaration for ChatClient
class ChatClient;
class MainWindow; // Forward declare MainWindow

class LoginWindow : public QDialog
{
    Q_OBJECT

public:
    // 修改构造函数以接收 ChatClient 指针
    explicit LoginWindow(ChatClient *client, QWidget *parent = nullptr);
    ~LoginWindow();

private slots:
    void on_loginButton_clicked();
    void on_registerButton_clicked();

    // Slots to handle ChatClient signals
    void handleLoginSucceeded(const QString &username, const QString &token);
    void handleLoginFailed(const QString &reason);
    void handleSocketError(const QString &errorString);
    void handleDisconnected(); // Handle server disconnection

private:
    Ui::LoginWindow *ui;
    ChatClient *m_chatClient; // 指向 ChatClient 实例
    MainWindow *m_mainWindow; // To show after login

    void attemptServerLogin(const QString &username, const QString &password);
};

#endif // LOGINWINDOW_H
